services:
  postgres:
    container_name: hist-arts_db
    image: postgres:15
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: HistArts_DB

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: histartsadm@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: histadmin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  admin:
    build: /admin
    container_name: hist-arts_admin
    env_file: /admin/.env
    ports:
      - 8800:80
    depends_on:
      - server
    restart: on-failure
    command: nginx -g 'daemon off;'


  client:
    build: /client
    container_name: hist-arts_client
    env_file: /client/.env
    ports:
      - "8088:80"
    depends_on:
      - server
    restart: on-failure
    command: nginx -g 'daemon off;'

  server:
    env_file: /server/.env
    container_name: hist-arts_server
    build: /server
    ports:
      - 0.0.0.0:3001:3001
    command: yarn server
    depends_on:
      - postgres
    restart: on-failure

volumes:
  pgadmin-data:
  data_postgres:
  # nginx-data: