networks:
  net:

services:
  postgres:
    container_name: hist-arts_db
    image: postgres:15
    env_file: ./server/.env.local
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - net

  admin:
    build: ./admin
    container_name: hist-arts_admin
    env_file: ./admin/.env.local
    depends_on:
      - server
    restart: on-failure
    networks:
      - net

  client:
    build: ./client
    container_name: hist-arts_client
    env_file: ./client/.env.local
    depends_on:
      - server
    restart: on-failure
    networks:
      - net

  server:
    env_file: ./server/.env.local
    container_name: hist-arts_server
    build: ./server
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - net
    command: yarn server
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - net

  certbot: 
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - net
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email vladislav.webdeveloper@gmail.com -d histarts.site -d www.histarts.site -d admin.histarts.site -d api.histarts.site --agree-tos
volumes:
  pgadmin-data:
  data_postgres: