services:
  postgres:
    container_name: hist-arts_db
    image: postgres:15
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:80
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: root

  admin:
    build: /admin
    container_name: hist-arts_admin
    env_file: /admin/.env.local
    ports:
      - 8800:80
    depends_on:
      - server
    restart: on-failure
    command: nginx -g 'daemon off;'


  client:
    build: /client
    container_name: hist-arts_client
    env_file: /client/.env.local
    ports:
      - "8088:80"
    depends_on:
      - server
    restart: on-failure
    command: nginx -g 'daemon off;'

  server:
    env_file: /server/.env.local
    container_name: hist-arts_server
    build: /server
    ports:
      - 3001:3001
    command: yarn server
    depends_on:
      - postgres
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  pgadmin-data:
  data_postgres: