networks:
  net:

services:
  postgres:
    container_name: hist-arts_db
    image: postgres:15
    env_file: ./server/.env.local
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - net

  admin:
    build: ./admin
    container_name: hist-arts_admin
    env_file: ./admin/.env.local
    depends_on:
      - server
    restart: on-failure
    networks:
      - net

  client:
    build: ./client
    container_name: hist-arts_client
    env_file: ./client/.env.local
    depends_on:
      - server
    restart: on-failure
    networks:
      - net

  server:
    env_file: ./server/.env.local
    container_name: hist-arts_server
    build: ./server
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - net
    command: yarn server
volumes:
  pgadmin-data:
  data_postgres: